version: "2"
services:
  web:
    restart: always
    build:
      context: .
      dockerfile: docker/production/Dockerfile
    env_file: docker/production/.env
    ports:
      - "80:80"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    ports:
      - "3306"
    volumes_from:
      - data


  data:
    image: mysql:5.7