version: "2"
services:
  web:
    restart: always
    build:
      context: .
      dockerfile: docker/production/Dockerfile
    env_file: docker/production/.env
    ports:
      - "80:80"
    depends_on:
      - mysql

  postgres:
    image: postgres:9.5
    ports:
      - "5432"
    volumes_from:
      - data

  data:
    image: postgres:9.5