default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: root
  host: 

development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test

production:
  <<: *default
  username: root
  database: app_production
  password: dbpass